version: '3.9'
services:
  # MySQL server
  db-server:
    image: "mysql:latest"
    container_name: db-server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: code_jays_db
      MYSQL_USER: password
      MYSQL_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5