CREATE TABLE IF NOT EXISTS image_entity (
    image_id binary(16) NOT NULL UNIQUE,
    image_name VARCHAR(255) NOT NULL,
    path VARCHAR(255) NOT NULL,
    media_type VARCHAR(255) NOT NULL,
    PRIMARY KEY (image_id)
);

CREATE TABLE IF NOT EXISTS password_reset_token (
    password_reset_token_id BIGINT NOT NULL AUTO_INCREMENT,
    created_at DATETIME NOT NULL,
    expire_at DATETIME NOT NULL,
    token VARCHAR(255) NOT NULL,
    PRIMARY KEY (password_reset_token_id)
);

CREATE TABLE IF NOT EXISTS app_user (
    user_id BIGINT NOT NULL AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    profile_picture_path VARCHAR(255) NOT NULL,
    account_enabled BOOLEAN NOT NULL,
    credentials_expired BOOLEAN NOT NULL,
    account_expired BOOLEAN NOT NULL,
    account_locked BOOLEAN NOT NULL,
    password_token_id BIGINT,
    PRIMARY KEY (user_id),
    FOREIGN KEY (password_token_id) REFERENCES password_reset_token (password_reset_token_id)
);

CREATE TABLE IF NOT EXISTS custom_role (
    role_id BIGINT NOT NULL AUTO_INCREMENT,
    role VARCHAR(255) NOT NULL,
    PRIMARY KEY (role_id),
    user_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES app_user (user_id)
);

CREATE TABLE IF NOT EXISTS SPRING_SESSION (
    PRIMARY_ID CHAR(36) NOT NULL,
    SESSION_ID CHAR(36) NOT NULL,
    CREATION_TIME BIGINT NOT NULL,
    LAST_ACCESS_TIME BIGINT NOT NULL,
    MAX_INACTIVE_INTERVAL INT NOT NULL,
    EXPIRY_TIME BIGINT NOT NULL,
    PRINCIPAL_NAME VARCHAR(100),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE IF NOT EXISTS SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL,
    ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES BLOB NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;